// Code generated by koinegen from the schema registry. DO NOT EDIT.
//
// namespace: com.example.payments-engineering
// stratum:   customer
// extends:   io.jenkins
// source:    com.example.payments-engineering.json

package payments

import (
	"github.com/sol-duara-inc/koine-go/cmd/koinegen/fixtures/strata/build"
	"github.com/sol-duara-inc/koine-go/koine"
	"github.com/sol-duara-inc/koine-go/koine/codec"
	"github.com/sol-duara-inc/koine-go/koine/selector"
)

// Finished is the shape a station awaits to be handed a FinishedDelivery.
func Finished() selector.Selector {
	return selector.Event("dev.cdevents.build.finished").At("build")
}

// FinishedDelivery is what a CUSTOMER station is constructed with when a
// build finishes.
//
// Every field of it is yours and nothing beyond it exists here: the border
// of the kingdom is this struct, and what a stratum does not contain does
// not exist for it.
type FinishedDelivery struct {
	koine.IsDelivery

	Subject      build.SubjectRef
	Outcome      koine.Outcome
	ArtifactID   build.ArtifactRef
	ExecutorNode string
	QueueWaitMS  int
	CostCenter   string
	PCIScope     bool

	// broker is the host standing below this station: unexported and
	// unreachable, because a body speaks verbs, never a broker.
	broker koine.Broker
}

// Projects names the utterance type this delivery is cut from.
func (FinishedDelivery) Projects() string { return "dev.cdevents.build.finished" }

// Namespace is the stratum this delivery projects to.
func (FinishedDelivery) Namespace() string { return "com.example.payments-engineering" }

// Bind wires the delivery to the host standing below it. Construction is
// delivery: the host binds at construction and koine/testing binds from the
// script. A station body never calls this — there is nothing in a body
// that holds a Broker to pass.
func (d FinishedDelivery) Bind(b koine.Broker) koine.Delivery {
	d.broker = b
	return d
}

// EncodeFields writes the delivery's whole kingdom, lineage first.
func (d FinishedDelivery) EncodeFields(w *codec.Writer) {
	w.Key("subject")
	w.String(string(d.Subject))
	w.Key("outcome")
	w.String(string(d.Outcome))
	w.Key("artifactId")
	w.String(string(d.ArtifactID))
	w.Key("executorNode")
	w.String(d.ExecutorNode)
	w.Key("queueWaitMs")
	w.Int(d.QueueWaitMS)
	w.Key("costCenter")
	w.String(d.CostCenter)
	w.Key("pciScope")
	w.Bool(d.PCIScope)
}

// DecodeField reads one projected key; anything else is skipped.
func (d *FinishedDelivery) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "subject":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.Subject = build.SubjectRef(v)
		return true, nil
	case "outcome":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.Outcome = koine.Outcome(v)
		return true, nil
	case "artifactId":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.ArtifactID = build.ArtifactRef(v)
		return true, nil
	case "executorNode":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.ExecutorNode = v
		return true, nil
	case "queueWaitMs":
		v, err := r.Int()
		if err != nil {
			return true, err
		}
		d.QueueWaitMS = v
		return true, nil
	case "costCenter":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.CostCenter = v
		return true, nil
	case "pciScope":
		v, err := r.Bool()
		if err != nil {
			return true, err
		}
		d.PCIScope = v
		return true, nil
	}
	return false, nil
}

// MarshalJSON renders the delivery without reflection.
func (d FinishedDelivery) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	d.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads the delivery from JSON already cut to its lineage.
func (d *FinishedDelivery) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, d.DecodeField)
}
