// Code generated by koinegen from the schema registry. DO NOT EDIT.
//
// namespace: com.example.payments-engineering
// stratum:   customer
// extends:   io.jenkins
// source:    com.example.payments-engineering.json

// Package payments is the customer stratum: private keys on top of the
// vendor's extension. The vendor is not aware of it, and that
// confidentiality costs nothing to keep because it cannot be broken.
package payments

import (
	"github.com/sol-duara-inc/koine-go/cmd/koinegen/fixtures/strata/build"
	"github.com/sol-duara-inc/koine-go/cmd/koinegen/fixtures/strata/jenkins"
	"github.com/sol-duara-inc/koine-go/koine"
	"github.com/sol-duara-inc/koine-go/koine/codec"
)

// PaymentsBuildFinished is a finished build as this customer speaks it,
// private keys included.
type PaymentsBuildFinished struct {
	jenkins.JenkinsBuildFinished // the agreement, embedded — running it is honoring it
	CostCenter                   string
	PCIScope                     bool
}

// EventType is the event type PaymentsBuildFinished carries on the record.
func (PaymentsBuildFinished) EventType() string { return "dev.cdevents.build.finished" }

// Namespace is the stratum PaymentsBuildFinished was declared at.
func (PaymentsBuildFinished) Namespace() string { return "com.example.payments-engineering" }

// SeedPaymentsBuildFinished seeds a whole PaymentsBuildFinished: this
// stratum's keys and every key it inherits. Objects are seeded whole at the
// deepest extension, so seeding lives here, at the owning stratum, and
// nowhere else.
func SeedPaymentsBuildFinished(subject build.SubjectRef, outcome koine.Outcome, artifactID build.ArtifactRef, executorNode string, queueWaitMS int, costCenter string, pciScope bool) PaymentsBuildFinished {
	return PaymentsBuildFinished{
		JenkinsBuildFinished: jenkins.SeedJenkinsBuildFinished(subject, outcome, artifactID, executorNode, queueWaitMS),
		CostCenter:           costCenter,
		PCIScope:             pciScope,
	}
}

// EncodeFields writes PaymentsBuildFinished's keys, in declaration order,
// into an open object. Inherited keys are written first, by the stratum that
// owns them.
func (x PaymentsBuildFinished) EncodeFields(w *codec.Writer) {
	x.JenkinsBuildFinished.EncodeFields(w)
	w.Key("costCenter")
	w.String(x.CostCenter)
	w.Key("pciScope")
	w.Bool(x.PCIScope)
}

// DecodeField reads one key. A key this stratum does not name is not its
// business: it is reported unhandled and skipped, which is how a projection
// tolerates the wire without ever seeing past its own border.
func (x *PaymentsBuildFinished) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "costCenter":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.CostCenter = v
		return true, nil
	case "pciScope":
		v, err := r.Bool()
		if err != nil {
			return true, err
		}
		x.PCIScope = v
		return true, nil
	}
	return x.JenkinsBuildFinished.DecodeField(key, r)
}

// MarshalJSON renders PaymentsBuildFinished without reflection: every key is
// named here, in source.
func (x PaymentsBuildFinished) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	x.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads PaymentsBuildFinished from JSON the host already cut
// to this stratum's lineage. Two walls, one semantic: the host projects
// before the guest sees bytes, and the type would not hold a foreign key
// even if one arrived.
func (x *PaymentsBuildFinished) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, x.DecodeField)
}
