// Code generated by koinegen from the schema registry. DO NOT EDIT.
//
// namespace: io.jenkins
// stratum:   vendor
// extends:   dev.cdevents.build
// source:    io.jenkins.json

// Package jenkins is the vendor stratum: the community agreement plus the
// keys this tool knows and the floor never will.
package jenkins

import (
	"github.com/sol-duara-inc/koine-go/cmd/koinegen/fixtures/strata/build"
	"github.com/sol-duara-inc/koine-go/koine"
	"github.com/sol-duara-inc/koine-go/koine/codec"
)

// JenkinsBuildFinished is a finished build as this vendor speaks it: the
// agreement, embedded, plus the vendor's own keys.
type JenkinsBuildFinished struct {
	build.BuildFinished // the agreement, embedded — running it is honoring it
	ExecutorNode        string
	QueueWaitMS         int
}

// EventType is the event type JenkinsBuildFinished carries on the record.
func (JenkinsBuildFinished) EventType() string { return "dev.cdevents.build.finished" }

// Namespace is the stratum JenkinsBuildFinished was declared at.
func (JenkinsBuildFinished) Namespace() string { return "io.jenkins" }

// SeedJenkinsBuildFinished seeds a whole JenkinsBuildFinished: this
// stratum's keys and every key it inherits. Objects are seeded whole at the
// deepest extension, so seeding lives here, at the owning stratum, and
// nowhere else.
func SeedJenkinsBuildFinished(subject build.SubjectRef, outcome koine.Outcome, artifactID build.ArtifactRef, executorNode string, queueWaitMS int) JenkinsBuildFinished {
	return JenkinsBuildFinished{
		BuildFinished: build.SeedBuildFinished(subject, outcome, artifactID),
		ExecutorNode:  executorNode,
		QueueWaitMS:   queueWaitMS,
	}
}

// EncodeFields writes JenkinsBuildFinished's keys, in declaration order,
// into an open object. Inherited keys are written first, by the stratum that
// owns them.
func (x JenkinsBuildFinished) EncodeFields(w *codec.Writer) {
	x.BuildFinished.EncodeFields(w)
	w.Key("executorNode")
	w.String(x.ExecutorNode)
	w.Key("queueWaitMs")
	w.Int(x.QueueWaitMS)
}

// DecodeField reads one key. A key this stratum does not name is not its
// business: it is reported unhandled and skipped, which is how a projection
// tolerates the wire without ever seeing past its own border.
func (x *JenkinsBuildFinished) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "executorNode":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.ExecutorNode = v
		return true, nil
	case "queueWaitMs":
		v, err := r.Int()
		if err != nil {
			return true, err
		}
		x.QueueWaitMS = v
		return true, nil
	}
	return x.BuildFinished.DecodeField(key, r)
}

// MarshalJSON renders JenkinsBuildFinished without reflection: every key is
// named here, in source.
func (x JenkinsBuildFinished) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	x.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads JenkinsBuildFinished from JSON the host already cut to
// this stratum's lineage. Two walls, one semantic: the host projects before
// the guest sees bytes, and the type would not hold a foreign key even if
// one arrived.
func (x *JenkinsBuildFinished) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, x.DecodeField)
}
