package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// The generator renders one Go package per registry namespace. Everything it
// emits is derivable from the namespace's own file plus the lineage it
// declares — never from what extends it — so a floor package's bytes do not
// move when a vendor or a customer is added. Byte-stability is not a
// courtesy to the golden test; it is the shape of downward blindness showing
// through the output.

const generatedHeader = "// Code generated by koinegen from the schema registry. DO NOT EDIT."

// ownedField is a field together with the type that declares it, so a
// generated file can name the field's Go type from the package that owns it.
type ownedField struct {
	Field
	owner *Type
}

func ownedFields(t *Type) []ownedField {
	var out []ownedField
	if t.Parent() != nil {
		out = ownedFields(t.Parent())
	}
	for _, f := range t.Fields {
		out = append(out, ownedField{Field: f, owner: t})
	}
	return out
}

// generator holds what every file needs: the judged registry and the import
// path the generated packages will live under.
type generator struct {
	reg     *Registry
	pkgBase string
}

// Generate writes the whole tree and returns the relative paths written. Any
// stale generated file under a namespace directory is removed, so deleting a
// namespace from the registry deletes its output rather than leaving a
// package nobody generates any more.
func Generate(reg *Registry, pkgBase, outDir string) ([]string, error) {
	files, err := GenerateFiles(reg, pkgBase)
	if err != nil {
		return nil, err
	}
	paths := make([]string, 0, len(files))
	for path := range files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	keep := map[string]bool{}
	for _, path := range paths {
		keep[path] = true
		full := filepath.Join(outDir, filepath.FromSlash(path))
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			return nil, err
		}
		if err := os.WriteFile(full, files[path], 0o644); err != nil {
			return nil, err
		}
	}
	stale, err := filepath.Glob(filepath.Join(outDir, "*", "*.gen.go"))
	if err != nil {
		return nil, err
	}
	for _, path := range stale {
		rel, err := filepath.Rel(outDir, path)
		if err != nil {
			return nil, err
		}
		if !keep[filepath.ToSlash(rel)] {
			if err := os.Remove(path); err != nil {
				return nil, err
			}
		}
	}
	return paths, nil
}

// GenerateFiles renders the tree in memory: relative slash-separated path to
// gofmt'd source.
func GenerateFiles(reg *Registry, pkgBase string) (map[string][]byte, error) {
	g := &generator{reg: reg, pkgBase: strings.TrimSuffix(pkgBase, "/")}
	files := map[string][]byte{}
	for _, ns := range reg.Namespaces {
		src, err := g.stratumFile(ns)
		if err != nil {
			return nil, err
		}
		files[ns.Package+"/stratum.gen.go"] = src
		if len(ns.Deliveries) > 0 {
			src, err := g.deliveryFile(ns)
			if err != nil {
				return nil, err
			}
			files[ns.Package+"/delivery.gen.go"] = src
		}
	}
	return files, nil
}

func (g *generator) importPath(ns *Namespace) string { return g.pkgBase + "/" + ns.Package }

const (
	koinePath    = "github.com/sol-duara-inc/koine-go/koine"
	codecPath    = "github.com/sol-duara-inc/koine-go/koine/codec"
	selectorPath = "github.com/sol-duara-inc/koine-go/koine/selector"
)

// goType renders a field type as the package `from` must spell it.
func (g *generator) goType(owner *Namespace, fieldType string, from *Namespace) string {
	if name, ok := strings.CutPrefix(fieldType, "ref:"); ok {
		refOwner := owner.RefOwner(name)
		if refOwner == from {
			return name
		}
		return refOwner.Package + "." + name
	}
	switch fieldType {
	case "outcome":
		return "koine.Outcome"
	default:
		return fieldType
	}
}

// header writes the provenance every generated file carries: which namespace
// it came from and which file in the registry said so.
func header(ns *Namespace) string {
	extends := "—  (the floor)"
	if ns.Extends != "" {
		extends = ns.Extends
	}
	return generatedHeader + "\n//\n" +
		"// namespace: " + ns.Namespace + "\n" +
		"// stratum:   " + ns.Stratum + "\n" +
		"// extends:   " + extends + "\n" +
		"// source:    " + ns.file + "\n\n"
}

func (g *generator) stratumFile(ns *Namespace) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header(ns))
	writeDoc(&b, "Package "+ns.Package+" is ", ns.Doc)
	fmt.Fprintf(&b, "package %s\n\n", ns.Package)

	imports := map[string]bool{koinePath: true, codecPath: true}
	for _, t := range ns.Types {
		if p := t.Parent(); p != nil {
			imports[g.importPath(p.Owner())] = true
		}
		for _, of := range ownedFields(t) {
			if name, ok := strings.CutPrefix(of.Type, "ref:"); ok {
				if refOwner := of.owner.Owner().RefOwner(name); refOwner != ns {
					imports[g.importPath(refOwner)] = true
				}
			}
		}
	}
	writeImports(&b, imports)

	if len(ns.Refs) > 0 {
		comment(&b, "Address types. A field that names what it points at is a field that cannot be handed the wrong string by accident.")
		b.WriteString("\n")
		for _, ref := range ns.Refs {
			writeDoc(&b, ref.Name+" ", ref.Doc)
			fmt.Fprintf(&b, "type %s string\n\n", ref.Name)
		}
	}

	for _, t := range ns.Types {
		g.writeType(&b, ns, t)
	}
	return format.Source([]byte(b.String()))
}

func (g *generator) writeType(b *strings.Builder, ns *Namespace, t *Type) {
	writeDoc(b, t.Name+" ", t.Doc)
	fmt.Fprintf(b, "type %s struct {\n", t.Name)
	if p := t.Parent(); p != nil {
		fmt.Fprintf(b, "\t%s.%s // the agreement, embedded — running it is honoring it\n", p.Owner().Package, p.Name)
	} else {
		b.WriteString("\tkoine.IsUtterance\n")
	}
	for _, f := range t.Fields {
		fmt.Fprintf(b, "\t%s %s\n", f.Name, g.goType(ns, f.Type, ns))
	}
	b.WriteString("}\n\n")

	comment(b, "EventType is the event type "+t.Name+" carries on the record.")
	fmt.Fprintf(b, "func (%s) EventType() string { return %q }\n\n", t.Name, t.Event)
	comment(b, "Namespace is the stratum "+t.Name+" was declared at.")
	fmt.Fprintf(b, "func (%s) Namespace() string { return %q }\n\n", t.Name, ns.Namespace)

	g.writeSeed(b, ns, t)
	g.writeCodec(b, ns, t)
}

// writeSeed emits the seeding constructor — at the OWNING stratum only, and
// taking the whole object: objects are seeded whole at the deepest extension
// (ruled 2026-07-21). A vendor's seeder calls the floor's, so the community
// agreement is honored by construction rather than copied.
func (g *generator) writeSeed(b *strings.Builder, ns *Namespace, t *Type) {
	fields := ownedFields(t)
	params := make([]string, 0, len(fields))
	for _, of := range fields {
		params = append(params, paramName(of.Name)+" "+g.goType(of.owner.Owner(), of.Type, ns))
	}
	comment(b, "Seed"+t.Name+" seeds a whole "+t.Name+": this stratum's keys and every key it inherits. Objects are seeded whole at the deepest extension, so seeding lives here, at the owning stratum, and nowhere else.")
	fmt.Fprintf(b, "func Seed%s(%s) %s {\n", t.Name, strings.Join(params, ", "), t.Name)
	fmt.Fprintf(b, "\treturn %s{\n", t.Name)
	if p := t.Parent(); p != nil {
		inherited := ownedFields(p)
		args := make([]string, 0, len(inherited))
		for _, of := range inherited {
			args = append(args, paramName(of.Name))
		}
		fmt.Fprintf(b, "\t\t%s: %s.Seed%s(%s),\n", p.Name, p.Owner().Package, p.Name, strings.Join(args, ", "))
	}
	for _, f := range t.Fields {
		fmt.Fprintf(b, "\t\t%s: %s,\n", f.Name, paramName(f.Name))
	}
	b.WriteString("\t}\n}\n\n")
}

// writeCodec emits hand-rolled marshal and unmarshal: every key named in
// source, nothing reflected, nothing read from a struct tag at run time.
// The Marshal/Unmarshal pair is re-declared at every stratum on purpose —
// embedding would otherwise promote the parent's pair, and a parent's
// marshaller would silently drop this stratum's keys. Divergence is by
// declaration here too.
func (g *generator) writeCodec(b *strings.Builder, ns *Namespace, t *Type) {
	comment(b, "EncodeFields writes "+t.Name+"'s keys, in declaration order, into an open object. Inherited keys are written first, by the stratum that owns them.")
	fmt.Fprintf(b, "func (x %s) EncodeFields(w *codec.Writer) {\n", t.Name)
	if p := t.Parent(); p != nil {
		fmt.Fprintf(b, "\tx.%s.EncodeFields(w)\n", p.Name)
	}
	for _, f := range t.Fields {
		writeEncodeField(b, "x."+f.Name, f)
	}
	b.WriteString("}\n\n")

	comment(b, "DecodeField reads one key. A key this stratum does not name is not its business: it is reported unhandled and skipped, which is how a projection tolerates the wire without ever seeing past its own border.")
	fmt.Fprintf(b, "func (x *%s) DecodeField(key string, r *codec.Reader) (bool, error) {\n", t.Name)
	if len(t.Fields) > 0 {
		b.WriteString("\tswitch key {\n")
		for _, f := range t.Fields {
			fmt.Fprintf(b, "\tcase %q:\n", f.JSON)
			writeDecodeField(b, "\t\t", "x."+f.Name, f, g.goType(ns, f.Type, ns))
		}
		b.WriteString("\t}\n")
	}
	if p := t.Parent(); p != nil {
		fmt.Fprintf(b, "\treturn x.%s.DecodeField(key, r)\n", p.Name)
	} else {
		b.WriteString("\treturn false, nil\n")
	}
	b.WriteString("}\n\n")

	comment(b, "MarshalJSON renders "+t.Name+" without reflection: every key is named here, in source.")
	fmt.Fprintf(b, "func (x %s) MarshalJSON() ([]byte, error) {\n", t.Name)
	b.WriteString("\tvar w codec.Writer\n\tw.BeginObject()\n\tx.EncodeFields(&w)\n\tw.EndObject()\n\treturn w.Bytes(), nil\n}\n\n")

	comment(b, "UnmarshalJSON reads "+t.Name+" from JSON the host already cut to this stratum's lineage. Two walls, one semantic: the host projects before the guest sees bytes, and the type would not hold a foreign key even if one arrived.")
	fmt.Fprintf(b, "func (x *%s) UnmarshalJSON(data []byte) error {\n", t.Name)
	b.WriteString("\treturn codec.DecodeObject(data, x.DecodeField)\n}\n\n")
}

func writeEncodeField(b *strings.Builder, expr string, f Field) {
	fmt.Fprintf(b, "\tw.Key(%q)\n", f.JSON)
	switch {
	case strings.HasPrefix(f.Type, "ref:"), f.Type == "outcome":
		fmt.Fprintf(b, "\tw.String(string(%s))\n", expr)
	case f.Type == "string":
		fmt.Fprintf(b, "\tw.String(%s)\n", expr)
	case f.Type == "int":
		fmt.Fprintf(b, "\tw.Int(%s)\n", expr)
	case f.Type == "bool":
		fmt.Fprintf(b, "\tw.Bool(%s)\n", expr)
	}
}

func writeDecodeField(b *strings.Builder, indent, expr string, f Field, goType string) {
	read, cast := "String", true
	switch f.Type {
	case "string":
		cast = false
	case "int":
		read, cast = "Int", false
	case "bool":
		read, cast = "Bool", false
	}
	fmt.Fprintf(b, "%sv, err := r.%s()\n", indent, read)
	fmt.Fprintf(b, "%sif err != nil {\n%s\treturn true, err\n%s}\n", indent, indent, indent)
	if cast {
		fmt.Fprintf(b, "%s%s = %s(v)\n", indent, expr, goType)
	} else {
		fmt.Fprintf(b, "%s%s = v\n", indent, expr)
	}
	fmt.Fprintf(b, "%sreturn true, nil\n", indent)
}

func writeDoc(b *strings.Builder, subject, doc string) {
	if doc == "" {
		return
	}
	comment(b, subject+doc)
}

// comment writes a wrapped doc comment, one paragraph per argument. Wrapping
// is fixed and deterministic so a registry edit shows up in the diff as the
// words that changed, not as a reflow.
func comment(b *strings.Builder, paragraphs ...string) {
	written := 0
	for _, p := range paragraphs {
		if p == "" {
			continue
		}
		if written > 0 {
			b.WriteString("//\n")
		}
		for _, line := range wrapDoc(p, 74) {
			b.WriteString("// " + line + "\n")
		}
		written++
	}
}

func wrapDoc(s string, width int) []string {
	words := strings.Fields(s)
	var lines []string
	line := ""
	for _, w := range words {
		switch {
		case line == "":
			line = w
		case len(line)+1+len(w) <= width:
			line += " " + w
		default:
			lines = append(lines, line)
			line = w
		}
	}
	if line != "" {
		lines = append(lines, line)
	}
	return lines
}

func writeImports(b *strings.Builder, imports map[string]bool) {
	if len(imports) == 0 {
		return
	}
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	b.WriteString("import (\n")
	for _, p := range paths {
		fmt.Fprintf(b, "\t%q\n", p)
	}
	b.WriteString(")\n\n")
}

var goKeywords = map[string]bool{
	"break": true, "case": true, "chan": true, "const": true, "continue": true,
	"default": true, "defer": true, "else": true, "fallthrough": true, "for": true,
	"func": true, "go": true, "goto": true, "if": true, "import": true,
	"interface": true, "map": true, "package": true, "range": true, "return": true,
	"select": true, "struct": true, "switch": true, "type": true, "var": true,
}

// paramName lowers an exported field name to a parameter name, keeping
// initialisms intact: ArtifactID becomes artifactID, PCIScope becomes
// pciScope.
func paramName(name string) string {
	run := 0
	for run < len(name) && name[run] >= 'A' && name[run] <= 'Z' {
		run++
	}
	var out string
	switch {
	case run == len(name):
		out = strings.ToLower(name)
	case run > 1:
		out = strings.ToLower(name[:run-1]) + name[run-1:]
	default:
		out = strings.ToLower(name[:1]) + name[1:]
	}
	if goKeywords[out] {
		return out + "_"
	}
	return out
}
