// Code generated by koinegen from the schema registry. DO NOT EDIT.
//
// namespace: dev.cdevents.deployment
// stratum:   floor
// extends:   —  (the floor)
// source:    dev.cdevents.deployment.json

package deployment

import (
	"github.com/sol-duara-inc/koine-go/koine"
	"github.com/sol-duara-inc/koine-go/koine/codec"
	"github.com/sol-duara-inc/koine-go/koine/selector"
)

// Resolved is the shape a station awaits to be handed a ResolvedDelivery.
func Resolved() selector.Selector {
	return selector.Resolved("dev.cdevents.deployment").At("deploy")
}

// ResolvedDelivery is what a station awaiting the completed deployment
// thought is constructed with.
//
// Every field of it is yours and nothing beyond it exists here: the border
// of the kingdom is this struct, and what a stratum does not contain does
// not exist for it.
type ResolvedDelivery struct {
	koine.IsDelivery

	Subject     SubjectRef
	Outcome     koine.Outcome
	ArtifactID  ArtifactRef
	Environment EnvironmentRef

	// broker is the host standing below this station: unexported and
	// unreachable, because a body speaks verbs, never a broker.
	broker koine.Broker
}

// Projects names the utterance type this delivery is cut from.
func (ResolvedDelivery) Projects() string { return "dev.cdevents.deployment.finished" }

// Namespace is the stratum this delivery projects to.
func (ResolvedDelivery) Namespace() string { return "dev.cdevents.deployment" }

// Bind wires the delivery to the host standing below it. Construction is
// delivery: the host binds at construction and koine/testing binds from the
// script. A station body never calls this — there is nothing in a body
// that holds a Broker to pass.
func (d ResolvedDelivery) Bind(b koine.Broker) koine.Delivery {
	d.broker = b
	return d
}

// EncodeFields writes the delivery's whole kingdom, lineage first.
func (d ResolvedDelivery) EncodeFields(w *codec.Writer) {
	w.Key("subject")
	w.String(string(d.Subject))
	w.Key("outcome")
	w.String(string(d.Outcome))
	w.Key("artifactId")
	w.String(string(d.ArtifactID))
	w.Key("environment")
	w.String(string(d.Environment))
}

// DecodeField reads one projected key; anything else is skipped.
func (d *ResolvedDelivery) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "subject":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.Subject = SubjectRef(v)
		return true, nil
	case "outcome":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.Outcome = koine.Outcome(v)
		return true, nil
	case "artifactId":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.ArtifactID = ArtifactRef(v)
		return true, nil
	case "environment":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		d.Environment = EnvironmentRef(v)
		return true, nil
	}
	return false, nil
}

// MarshalJSON renders the delivery without reflection.
func (d ResolvedDelivery) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	d.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads the delivery from JSON already cut to its lineage.
func (d *ResolvedDelivery) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, d.DecodeField)
}

// History opens the seat that answers from the record. History is just
// another awaited shape: every past emission was already a write, so there
// is no query surface and no second convention.
//
// It opens the "history" seat. An unfilled seat is refused at registration
// by name — the honest terminus, before runtime — never discovered in
// here.
func (d ResolvedDelivery) History() HistorySeat {
	return HistorySeat{broker: d.broker}
}

// Ledger opens the seat that keeps the deployment ledger.
//
// It opens the "ledger" seat. An unfilled seat is refused at registration by
// name — the honest terminus, before runtime — never discovered in here.
func (d ResolvedDelivery) Ledger() LedgerSeat {
	return LedgerSeat{broker: d.broker}
}

// HistorySeat is the "history" seat, curried with the station's context at
// construction. A body speaks intents at it; it never names a tool and it
// never names an address. The operator owns the address and the credential,
// and the deployment binds the client.
type HistorySeat struct{ broker koine.Broker }

// Last asks the record for the most recent deployment that ended with the
// given outcome.
//
// It speaks "history.last" — an intent, uttered at the call. How you use
// the handle IS the branch control: Value() consumed is inline, spoken and
// never consumed is concurrent.
func (v HistorySeat) Last(outcome koine.Outcome) koine.Handle[DeploymentFinished] {
	h := &handleDeploymentFinished{
		broker: v.broker,
		exchange: koine.Exchange{
			Seat: "history",
			Name: "history.last",
			Args: []koine.Arg{
				{Name: "outcome", Value: string(outcome)},
			},
		},
	}
	h.speak()
	return h
}

// LedgerSeat is the "ledger" seat, curried with the station's context at
// construction. A body speaks intents at it; it never names a tool and it
// never names an address. The operator owns the address and the credential,
// and the deployment binds the client.
type LedgerSeat struct{ broker koine.Broker }

// Note asks the ledger to carry a note beside the deployment.
//
// It speaks "ledger.note" — an intent, uttered at the call. How you use
// the handle IS the branch control: Value() consumed is inline, spoken and
// never consumed is concurrent.
func (v LedgerSeat) Note(text string) koine.Handle[DeploymentRecorded] {
	h := &handleDeploymentRecorded{
		broker: v.broker,
		exchange: koine.Exchange{
			Seat: "ledger",
			Name: "ledger.note",
			Args: []koine.Arg{
				{Name: "text", Value: text},
			},
		},
	}
	h.speak()
	return h
}

// handleDeploymentFinished gates on an exchange answering with
// DeploymentFinished.
type handleDeploymentFinished struct {
	broker   koine.Broker
	exchange koine.Exchange
	answer   *koine.Answer
}

// speak utters the intent once. With no host below the station it panics: an
// exchange never fails silently, and a nil answer is not an answer.
func (h *handleDeploymentFinished) speak() {
	if h.answer != nil {
		return
	}
	if h.broker == nil {
		panic("koine: " + h.exchange.Name + " spoke with no host below this station — an exchange never fails silently")
	}
	a := h.broker.Speak(h.exchange)
	h.answer = &a
}

// Received is the fast beat: someone who declared comprehension has this
// now.
func (h *handleDeploymentFinished) Received() koine.Ack {
	h.speak()
	return koine.Ack{By: h.answer.By}
}

// Value gates on completion and materializes the answer. The error is the
// typed outcome variant of the expected response, never transport — branch
// on it, don't defend against it.
func (h *handleDeploymentFinished) Value() (DeploymentFinished, error) {
	h.speak()
	h.broker.Consumed(h.exchange)
	var v DeploymentFinished
	if h.answer.Err != nil {
		return v, h.answer.Err
	}
	if len(h.answer.JSON) == 0 {
		return v, nil
	}
	if err := v.UnmarshalJSON(h.answer.JSON); err != nil {
		return v, err
	}
	return v, nil
}

// handleDeploymentRecorded gates on an exchange answering with
// DeploymentRecorded.
type handleDeploymentRecorded struct {
	broker   koine.Broker
	exchange koine.Exchange
	answer   *koine.Answer
}

// speak utters the intent once. With no host below the station it panics: an
// exchange never fails silently, and a nil answer is not an answer.
func (h *handleDeploymentRecorded) speak() {
	if h.answer != nil {
		return
	}
	if h.broker == nil {
		panic("koine: " + h.exchange.Name + " spoke with no host below this station — an exchange never fails silently")
	}
	a := h.broker.Speak(h.exchange)
	h.answer = &a
}

// Received is the fast beat: someone who declared comprehension has this
// now.
func (h *handleDeploymentRecorded) Received() koine.Ack {
	h.speak()
	return koine.Ack{By: h.answer.By}
}

// Value gates on completion and materializes the answer. The error is the
// typed outcome variant of the expected response, never transport — branch
// on it, don't defend against it.
func (h *handleDeploymentRecorded) Value() (DeploymentRecorded, error) {
	h.speak()
	h.broker.Consumed(h.exchange)
	var v DeploymentRecorded
	if h.answer.Err != nil {
		return v, h.answer.Err
	}
	if len(h.answer.JSON) == 0 {
		return v, nil
	}
	if err := v.UnmarshalJSON(h.answer.JSON); err != nil {
		return v, err
	}
	return v, nil
}
