// Code generated by koinegen from the schema registry. DO NOT EDIT.
//
// namespace: dev.cdevents.deployment
// stratum:   floor
// extends:   —  (the floor)
// source:    dev.cdevents.deployment.json

// Package deployment is the community floor for deployment events — the
// stratum the design document's worked example stands on.
package deployment

import (
	"github.com/sol-duara-inc/koine-go/koine"
	"github.com/sol-duara-inc/koine-go/koine/codec"
)

// Address types. A field that names what it points at is a field that cannot
// be handed the wrong string by accident.

// SubjectRef addresses the subject a deployment event is about.
type SubjectRef string

// ArtifactRef addresses a deployable artifact in the record.
type ArtifactRef string

// EnvironmentRef addresses an environment a deployment targets.
type EnvironmentRef string

// DeploymentFinished is a deployment that reached a terminal state —
// either outcome. The resolved idiom delivers the completed thought and the
// body branches; the declaration never filters.
type DeploymentFinished struct {
	koine.IsUtterance
	Subject     SubjectRef
	Outcome     koine.Outcome
	ArtifactID  ArtifactRef
	Environment EnvironmentRef
}

// EventType is the event type DeploymentFinished carries on the record.
func (DeploymentFinished) EventType() string { return "dev.cdevents.deployment.finished" }

// Namespace is the stratum DeploymentFinished was declared at.
func (DeploymentFinished) Namespace() string { return "dev.cdevents.deployment" }

// SeedDeploymentFinished seeds a whole DeploymentFinished: this stratum's
// keys and every key it inherits. Objects are seeded whole at the deepest
// extension, so seeding lives here, at the owning stratum, and nowhere else.
func SeedDeploymentFinished(subject SubjectRef, outcome koine.Outcome, artifactID ArtifactRef, environment EnvironmentRef) DeploymentFinished {
	return DeploymentFinished{
		Subject:     subject,
		Outcome:     outcome,
		ArtifactID:  artifactID,
		Environment: environment,
	}
}

// EncodeFields writes DeploymentFinished's keys, in declaration order, into
// an open object. Inherited keys are written first, by the stratum that owns
// them.
func (x DeploymentFinished) EncodeFields(w *codec.Writer) {
	w.Key("subject")
	w.String(string(x.Subject))
	w.Key("outcome")
	w.String(string(x.Outcome))
	w.Key("artifactId")
	w.String(string(x.ArtifactID))
	w.Key("environment")
	w.String(string(x.Environment))
}

// DecodeField reads one key. A key this stratum does not name is not its
// business: it is reported unhandled and skipped, which is how a projection
// tolerates the wire without ever seeing past its own border.
func (x *DeploymentFinished) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "subject":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.Subject = SubjectRef(v)
		return true, nil
	case "outcome":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.Outcome = koine.Outcome(v)
		return true, nil
	case "artifactId":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.ArtifactID = ArtifactRef(v)
		return true, nil
	case "environment":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.Environment = EnvironmentRef(v)
		return true, nil
	}
	return false, nil
}

// MarshalJSON renders DeploymentFinished without reflection: every key is
// named here, in source.
func (x DeploymentFinished) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	x.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads DeploymentFinished from JSON the host already cut to
// this stratum's lineage. Two walls, one semantic: the host projects before
// the guest sees bytes, and the type would not hold a foreign key even if
// one arrived.
func (x *DeploymentFinished) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, x.DecodeField)
}

// DeploymentRecorded says a deployment was taken into the record. Emitting
// it IS the storage action; there is no separate write.
type DeploymentRecorded struct {
	koine.IsUtterance
	Artifact ArtifactRef
}

// EventType is the event type DeploymentRecorded carries on the record.
func (DeploymentRecorded) EventType() string { return "dev.cdevents.deployment.recorded" }

// Namespace is the stratum DeploymentRecorded was declared at.
func (DeploymentRecorded) Namespace() string { return "dev.cdevents.deployment" }

// SeedDeploymentRecorded seeds a whole DeploymentRecorded: this stratum's
// keys and every key it inherits. Objects are seeded whole at the deepest
// extension, so seeding lives here, at the owning stratum, and nowhere else.
func SeedDeploymentRecorded(artifact ArtifactRef) DeploymentRecorded {
	return DeploymentRecorded{
		Artifact: artifact,
	}
}

// EncodeFields writes DeploymentRecorded's keys, in declaration order, into
// an open object. Inherited keys are written first, by the stratum that owns
// them.
func (x DeploymentRecorded) EncodeFields(w *codec.Writer) {
	w.Key("artifact")
	w.String(string(x.Artifact))
}

// DecodeField reads one key. A key this stratum does not name is not its
// business: it is reported unhandled and skipped, which is how a projection
// tolerates the wire without ever seeing past its own border.
func (x *DeploymentRecorded) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "artifact":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.Artifact = ArtifactRef(v)
		return true, nil
	}
	return false, nil
}

// MarshalJSON renders DeploymentRecorded without reflection: every key is
// named here, in source.
func (x DeploymentRecorded) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	x.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads DeploymentRecorded from JSON the host already cut to
// this stratum's lineage. Two walls, one semantic: the host projects before
// the guest sees bytes, and the type would not hold a foreign key even if
// one arrived.
func (x *DeploymentRecorded) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, x.DecodeField)
}

// Deploy asks for an artifact to be put on an environment. It is speech:
// whoever declared comprehension of it will hear it, and nobody else will.
type Deploy struct {
	koine.IsUtterance
	Artifact ArtifactRef
	Target   EnvironmentRef
}

// EventType is the event type Deploy carries on the record.
func (Deploy) EventType() string { return "dev.cdevents.deployment.requested" }

// Namespace is the stratum Deploy was declared at.
func (Deploy) Namespace() string { return "dev.cdevents.deployment" }

// SeedDeploy seeds a whole Deploy: this stratum's keys and every key it
// inherits. Objects are seeded whole at the deepest extension, so seeding
// lives here, at the owning stratum, and nowhere else.
func SeedDeploy(artifact ArtifactRef, target EnvironmentRef) Deploy {
	return Deploy{
		Artifact: artifact,
		Target:   target,
	}
}

// EncodeFields writes Deploy's keys, in declaration order, into an open
// object. Inherited keys are written first, by the stratum that owns them.
func (x Deploy) EncodeFields(w *codec.Writer) {
	w.Key("artifact")
	w.String(string(x.Artifact))
	w.Key("target")
	w.String(string(x.Target))
}

// DecodeField reads one key. A key this stratum does not name is not its
// business: it is reported unhandled and skipped, which is how a projection
// tolerates the wire without ever seeing past its own border.
func (x *Deploy) DecodeField(key string, r *codec.Reader) (bool, error) {
	switch key {
	case "artifact":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.Artifact = ArtifactRef(v)
		return true, nil
	case "target":
		v, err := r.String()
		if err != nil {
			return true, err
		}
		x.Target = EnvironmentRef(v)
		return true, nil
	}
	return false, nil
}

// MarshalJSON renders Deploy without reflection: every key is named here, in
// source.
func (x Deploy) MarshalJSON() ([]byte, error) {
	var w codec.Writer
	w.BeginObject()
	x.EncodeFields(&w)
	w.EndObject()
	return w.Bytes(), nil
}

// UnmarshalJSON reads Deploy from JSON the host already cut to this
// stratum's lineage. Two walls, one semantic: the host projects before the
// guest sees bytes, and the type would not hold a foreign key even if one
// arrived.
func (x *Deploy) UnmarshalJSON(data []byte) error {
	return codec.DecodeObject(data, x.DecodeField)
}
